var dir_a6086b4e9214f927ac65b0e33779efbe =
[
    [ "AddBook_func.cpp", "_add_book__func_8cpp.html", null ],
    [ "AddBook_func.h", "_add_book__func_8h.html", "_add_book__func_8h" ],
    [ "Borrow_book_functions.cpp", "_borrow__book__functions_8cpp.html", null ],
    [ "Borrow_book_functions.h", "_borrow__book__functions_8h.html", "_borrow__book__functions_8h" ],
    [ "connection_sql_func.cpp", "connection__sql__func_8cpp.html", "connection__sql__func_8cpp" ],
    [ "connection_sql_func.h", "connection__sql__func_8h.html", "connection__sql__func_8h" ],
    [ "delete_profile_func.cpp", "delete__profile__func_8cpp.html", null ],
    [ "delete_profile_func.h", "delete__profile__func_8h.html", "delete__profile__func_8h" ],
    [ "filling_datagrid.cpp", "filling__datagrid_8cpp.html", null ],
    [ "filling_datagrid.h", "filling__datagrid_8h.html", "filling__datagrid_8h" ],
    [ "fine_function.cpp", "fine__function_8cpp.html", "fine__function_8cpp" ],
    [ "fine_function.h", "fine__function_8h.html", "fine__function_8h" ],
    [ "login_to_librarian_db.cpp", "login__to__librarian__db_8cpp.html", "login__to__librarian__db_8cpp" ],
    [ "login_to_librarian_db.h", "login__to__librarian__db_8h.html", "login__to__librarian__db_8h" ],
    [ "RegisterLibrarian_func.cpp", "_register_librarian__func_8cpp.html", null ],
    [ "RegisterLibrarian_func.h", "_register_librarian__func_8h.html", "_register_librarian__func_8h" ],
    [ "RegisterMember_func.cpp", "_register_member__func_8cpp.html", null ],
    [ "RegisterMember_func.h", "_register_member__func_8h.html", "_register_member__func_8h" ],
    [ "Return_book_functions.cpp", "_return__book__functions_8cpp.html", null ],
    [ "Return_book_functions.h", "_return__book__functions_8h.html", "_return__book__functions_8h" ],
    [ "update_profile_func.cpp", "update__profile__func_8cpp.html", null ],
    [ "update_profile_func.h", "update__profile__func_8h.html", "update__profile__func_8h" ]
];